
[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-steputils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-xcode"

[[constraint]]
  name = "github.com/bitrise-steplib/steps-xcode-archive"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
