[[constraint]]
  name = "github.com/bitrise-io/steps-xcode-archive"
  version = "2.4.9"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-tools/go-steputils"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  name = "github.com/bitrise-tools/go-xcode"
  revision = "2bf5450263c607455557eeda2a982d00635b9c05"
